#include<conio.h>
#include<stdio.h>

 void main()
{
 clrscr();



 printf("\n           ?                                            ²²²²²²²²²² ²²²²²²²²²² ");
 printf("\n        ARRMANDO©           ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»       ²²²²²²²²²² ²²²²²²²²²²    ");
 printf("\n       ÛÛÛÛÛÛÛÛÛÛ           º®®®®® W T ¯¯¯¯¯º 	²²²²²²²²²² ²²²²²²²²²²    ");
 printf("\n       ±±==ÛÛ==±±           º®®®®® E O ¯¯¯¯¯º                               ");
 printf("\n       ÛÛÛÛÛÛÛÛÛÛ           º®®®®® L   ¯¯¯¯¯º        ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»");
 printf("\n       ÛÛÛÛ  ÛÛÛÛ           º®®®®® C T ¯¯¯¯¯º        º                º    ");
 printf("\n      °°°°°°°°°°°°          º®®®®® O U ¯¯¯¯¯º                        º ");
 printf("\n        °°°°°°°°      ÉÍÍ»  º®®®®® M R ¯¯¯¯¯º        Å                º  ");
 printf("\n         ÛÛÛÛÛÛ       ºHIº  º®®®®® E C ¯¯¯¯¯º                         º      ");
printf("\n{7±±ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±7}  ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼                         º   ");
 printf("\n        Û’ÛÛÛÛÛÛ                 		                   ''''''''          ");
 printf("   ÛÛÛÛÛÛÛÛ                                  ");
 printf("\n        ÛÛÛÛÛÛÛÛ                      COME ON!                                       ");
 printf("   ÛÛÛÛÛÛÛÛ                    ²²²²²²²²²²²²² ");
 printf("\n         ±±±±±±                   ²²²²²²²²²²²²²²²²²");
 printf("\n         ÛÛ  ÛÛ                 ²²²²²²²²²²²²²²²²²²²²²");
 printf("\n         ÛÛ  ÛÛ               ²²²²²²²²²²²²²²²²²²²²²²²²²      ");
 printf("\n         ÛÛ  ÛÛ             ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²      ÉÍÍÍÍÍÍ»");
 printf("\n         ÛÛ  ÛÛ           ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²    º 100% º  ");
 printf("\n         ±±  ±±         ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²² ÈÍÍÍÍÍÍ¼  ");
 printf("\n               ²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²²");
 printf("\n   '''''''''''''''''''                         ");
 printf("\n  ''''''''''''''''''''''        ");
 printf("\n ''''''''''''''''''''''''     ");
 getch();

 }