#include <stdio.h>
#include <conio.h>

int main ()
{
	clrscr();
	printf("ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»");
	printf("º°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°º");
	printf("º°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±º");
	printf("º±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²º");
	printf("º²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þº");
	printf("ºþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²º");
	printf("º²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±º");
	printf("Î       _____                 /                    \\                 _____     Î");
	printf("Î            \\               /                      \\               /          Î");
	printf("Î             \\             /     \\     \\            \\             /           Î");
	printf("Î              \\           ³       \\     \\      /     ³           /            Î");
	printf("Î               \\          ³                   /      ³          /             Î");
	printf("Î                \\          \\           ______/      /          /              Î");
	printf("Î                 \\__________\\                      /__________/               Î");
	printf("Î                             \\                    /                           Î");
	printf("º±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°º");
	printf("º°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°º");
	printf("º°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±º");
	printf("º±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²º");
	printf("º²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þº");
	printf("ºþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²º");
	printf("º²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±º");
	printf("º±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þþ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°±²þ²±°°º");
	printf("ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼");

	getch();
	return 0;
}