%Numero 3
x = linspace(-2*pi,2*pi,200);

%Grafica 3.1
Y = abs(power(x,x)-4);
plot(Y,'--gs',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[0.5,0.5,0.5])
figure;

%Grafica 3.2
Y = sin(3*x);
plot(Y,'--gs',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.5,0.5,0.5])
figure;

%Grafica 3.3
Y = exp(x);
plot(Y,'--gs',...
    'LineWidth',2,...
    'MarkerSize',10,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
grid on;
figure;

%Numero 4
%Grafica 4.1
subplot (3,1,1);
Y = power(x,2);

plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[0.5,0.5,0.5])
title('-2\pi >= x <= 2\pi');
ylabel('Y = x^2');
grid on;

%Grafica 4.2
subplot (3,1,2);
Y = 4*Y;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = 4x^2');
title('-2\pi >= x <= 2\pi');
grid on;

%Grafica 4.3
subplot (3,1,3);
Y = Y/8;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = x^2/2');
title('-2\pi >= x <= 2\pi');
grid on;
figure

%Numero 5
%Grafica 5.1.1
subplot (2,3,1);
Y = abs(power(x,x)-4);
plot(Y,'--gs',...
'LineWidth',2,...
'MarkerSize',5,...
'MarkerEdgeColor','c',...
'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = x^x - 4');
grid on;

%Grafica 5.1.2
subplot (2,3,2);
Y = sin(3*x);
plot(Y,'--gs',...
'LineWidth',2,...
'MarkerSize',5,...
'MarkerEdgeColor','g',...
'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = sin(3x)');
grid on;

%Grafica 5.1.3
subplot (2,3,3);
Y = exp(x);
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = e^x');
grid on;

%Grafica 5.1.4
subplot (2,3,4);
Y = power(x,2);

plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor',[0.5,0.5,0.5])
title('-2\pi >= x <= 2\pi');
ylabel('Y = x^2');
grid on;

%Grafica 5.1.5
subplot (2,3,5);
Y = 4*Y;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = 4x^2');
title('-2\pi >= x <= 2\pi');
grid on;

%Grafica 5.1.6
subplot (2,3,6);
Y = Y/8;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = x^2/2');
title('-2\pi >= x <= 2\pi');
grid on;
figure
%Grafica 5.2.1
subplot (3,2,1);
Y = abs(power(x,x)-4);
plot(Y,'--gs',...
'LineWidth',2,...
'MarkerSize',5,...
'MarkerEdgeColor','c',...
'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = x^x - 4');
grid on;

%Grafica 5.2.2
subplot (3,2,2);
Y = sin(3*x);
plot(Y,'--gs',...
'LineWidth',2,...
'MarkerSize',5,...
'MarkerEdgeColor','c',...
'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = sin(x)');
grid on;

%Grafica 5.2.3
subplot (3,2,3);
Y = exp(x);
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = e^x');
grid on;

%Grafica 5.2.4
subplot (3,2,4);
Y = power(x,2);

plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor',[0.5,0.5,0.5])
title('-2\pi >= x <= 2\pi');
ylabel('Y = x^2');
grid on;

%Grafica 5.2.5
subplot (3,2,5);
Y = 4*Y;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = 4x^2');
title('-2\pi >= x <= 2\pi');
grid on;

%Grafica 5.2.6
subplot (3,2,6);
Y = Y/8;
plot(Y,'--gs',...
    'LineWidth',2,...	
    'MarkerSize',5,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor',[0.5,0.5,0.5])
ylabel('Y = x^2/2');
title('-2\pi >= x <= 2\pi');
grid on;


