#INCLUDE <STDLIB.H>
#INCLUDE <STDIO.H>

INT MAIN(INT ARG, CHAR *ARGV[]){
  file *ORIGNPTR=null, *DESTNPTR=null;
  CHAR C;
  INT B=0;
  IF((ARG<2)){
    PRINTF("fALTA NOMBRE DE ARCHIVO");
    EXIT(-1);
  }
  ORIGNPTR = FOPEN(ARGV[1],"R");
  IF(!ORIGNPTR){
    PRINTF("eRROR AL ABRIR EL ARCHIVO %S", ARGV[1]);
    EXIT(-1);
  }
  IF (ARG==3){
    DESTNPTR = FOPEN(ARGV[2],"W");
    B=1;
    IF(!DESTNPTR){
      PRINTF("eRROR AL ABRIR EL ARCHIVO %S", ARGV[2]);
      EXIT(-1);
    } 
  }
  DO{
    C=FGETC(ORIGNPTR);
    IF (C>64 && C<91) C+=32;
    ELSE IF (C>96 && C<123) C-=32; 
    IF(ARG>2) FPRINTF(DESTNPTR, "%C", C);
    ELSE  PRINTF("%C", C);
  }WHILE(C!=eof);
  FCLOSE(ORIGNPTR); 
  FCLOSE(DESTNPTR);
  RETURN 0;  
}ÿ