inicio-programa

        entero a
        entero b

        leer "Ingresar valor de A: ", a
        leer "Ingresar valor de B: ", b

        si (a > b) entonces
                escribir "A es mayor que B"
        fin-entonces
        fin-si

        si (b > a) entonces
                escribir "B es mayor que A"
        fin-entonces
        fin-si

        si (a == b) entonces
                escribir "A y B son iguales"
        fin-entonces
        fin-si

fin-programa